server:
  port: 8181

web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    allowed-headers: "*"
    exposed-headers: "*"

spring:
  application :
    name : AuthService

  datasource:
    url: jdbc:postgresql://ep-solitary-dust-a558goh0.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=HK0GZyRcz9lh&sslmode=require
    username: neondb_owner
    password: HK0GZyRcz9lh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl:
        auto: update

eureka:
  client:
    fetch-registry : true
    register-with-eureka : true
    service-url:
      defaultZone : http://localhost:8182/eureka/

jwt:
  secretKey : afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf